version: '2'
services:
  db:
    image: postgres:9.6.3-alpine
    ports:
      - "5432:5432"
    volumes:
      # - "../build/pgdata:/var/lib/postgresql/data/pgdata"
      - postgres-volume:/var/lib/posgresql:Z
    environment:
      POSTGRES_PASSWORD: example
      PGDATA: "/var/lib/postgresql/data/pgdata"

  server:
    image: stac-dev:latest
    # command: ["./wait-for-db.sh", "db", "--", "yarn install && yarn run dev-server"]
    volumes:
      # - ../node_modules:/opt/app/node_modules
      - ../package.json:/opt/app/package.json
      - ../yarn.lock:/opt/app/yarn.lock
      - ../cards:/opt/app/cards
      - ../lang:/opt/app/lang
      - ../lib:/opt/app/lib
      - ../maps:/opt/app/maps
      - ../migrations:/opt/app/migrations
      - ../server:/opt/app/server
      - ../tests:/opt/app/tests
    ports:
      - "10123:10123"
    links:
      - db
    environment:
      - COMPONENTS=auth,game,lobby,log,site
      - DATABASE_URL=postgres://postgres:example@db/postgres
      - PG_USE_SSL=false
      - DEBUG=*,-nodemon*,-express*,-send,-body-parser*,-compression,-billy*,-babel*,-SocketClient*,-ComponentManager,-SocketServer,-SockHarness,-WrappedEmitter
      - DEBUG_COLORS=true
      - PORT=10123
      - PUBLIC_URL=http://192.168.1.155:10123
      - PING_INTERVAL=30000
      - CLIENT_LOG=./centauri-tac/client_log.json
      - DISCONNECT_TIMEOUT=5000
      - DEV=${DEV}
      - TESTING_CARDS=${TESTING_CARDS}
      - CARD_SETS=${CARD_SETS}
      - MAP=${MAP}
      - TURN_LENGTH_MS=${TURN_LENGTH_MS}
      - TURN_END_BUFFER_LENGTH_MS=${TURN_END_BUFFER_LENGTH_MS}
      - TURN_INCREMENT_LENGTH_MS=${TURN_INCREMENT_LENGTH_MS}

volumes:
  postgres-volume:
    external: true