version: '2.1'
services:
  db:
    image: postgres:9.6.3-alpine
    volumes:
      - "~/pgdata:/var/lib/postgresql/data/pgdata"
    environment:
      POSTGRES_PASSWORD: example
      PGDATA: "/var/lib/postgresql/data/pgdata"

  server:
    image: 423867126755.dkr.ecr.us-east-2.amazonaws.com/solaria:latest
    ports:
      - "10123:10123"
    links:
      - db
    environment:
      - COMPONENTS=auth,game,lobby,log
      - DATABASE_URL=postgres://postgres:example@db/postgres
      - PG_USE_SSL=false
      - DEBUG=*,-nodemon*,-express*,-send,-body-parser*,-compression,-billy*,-babel*,-SocketClient*,-ComponentManager,-SocketServer,-SockHarness,-WrappedEmitter
      - DEBUG_COLORS=true
      - PORT=10123
      - PUBLIC_URL=http://server.solaria.online:10123
      - PING_INTERVAL=30000
      - DISCONNECT_TIMEOUT=5000
      - VIRTUAL_HOST=server.solaria.online
      - VIRTUAL_PORT=10123
      - DEV=${DEV}
      - TESTING_CARDS=${TESTING_CARDS}
      - CARD_SETS=${CARD_SETS}
      - MAP=${MAP}
      - TURN_LENGTH_MS=${TURN_LENGTH_MS}
      - TURN_END_BUFFER_LENGTH_MS=${TURN_END_BUFFER_LENGTH_MS}
      - TURN_INCREMENT_LENGTH_MS=${TURN_INCREMENT_LENGTH_MS}
